import { AgentData } from '@/components/learn/AgentCard';

export const AGENTS: AgentData[] = [
  {
    name: 'planner',
    icon: '📋',
    description: 'Kreira implementacioni plan pre pisanja koda. Obavezan za svaki feature i netrivijalan bug fix.',
    category: 'Workflow',
    whenUsed: 'Pre svake implementacije. Student mora da odobri plan pre nego što se piše kod.',
    example: '/start-feature "dodaj logout dugme" → planner kreira plan sa koracima, fajlovima, i pristupom',
    calledBy: 'Korisnik preko /start-feature komande',
  },
  {
    name: 'implementer',
    icon: '⌨️',
    description: 'Prevodi odobreni plan u kod. Striktno odbija rad bez odobrenog plana.',
    category: 'Workflow',
    whenUsed: 'Posle odobrenja plana od strane korisnika. Nikad ne radi sam bez plana.',
    example: 'Plan kaže "dodaj endpoint POST /api/v1/auth/logout" → implementer piše route, controller, test',
    calledBy: 'Automatski posle odobrenja plana',
  },
  {
    name: 'test-writer',
    icon: '✍️',
    description: 'Piše nove testove (unit, integracione, frontend) za novu funkcionalnost ili regresiju.',
    category: 'Verifikacija',
    whenUsed: 'Posle implementacije, da se osigura da novi kod ima testove.',
    example: 'Napisan nov endpoint → test-writer piše testove za sve scenarije (uspeh, validacija, auth)',
    calledBy: 'Implementer ili korisnik',
  },
  {
    name: 'test-runner',
    icon: '🏃',
    description: 'Pokreće test suite, parsira rezultate i vraća strukturiran izveštaj. Ne menja kod.',
    category: 'Verifikacija',
    whenUsed: 'Kad treba proveriti da li testovi prolaze. Ulazna tačka u verifikacionu petlju.',
    example: 'npm test → 768/768 pass (49 suites) — ili — 3 failing, evo detalja...',
    calledBy: 'verification-orchestrator, korisnik',
  },
  {
    name: 'code-reviewer',
    icon: '🔍',
    description: 'Pregleda izmene koda pre commit-a. Proverava kvalitet, čitljivost, anti-paterne.',
    category: 'Kvalitet',
    whenUsed: 'Pre svakog commit-a. Pokreće se kroz /review komandu.',
    example: '/review → "Promenljiva `x` bi trebalo da ima opisnije ime. Console.log na liniji 45 treba obrisati."',
    calledBy: 'Korisnik preko /review',
  },
  {
    name: 'security-auditor',
    icon: '🛡️',
    description: 'Sigurnosni pregled izmena — OWASP top 10, curenje tajni, nepouzdani inputi.',
    category: 'Kvalitet',
    whenUsed: 'Kada izmene dodiruju auth, API, validaciju ili env fajlove.',
    example: 'Novi auth endpoint → provera: SQL injection, XSS, JWT slabosti, hardkodirane tajne',
    calledBy: 'Uslovno od strane code-reviewer-a',
  },
  {
    name: 'performance-analyzer',
    icon: '⚡',
    description: 'Analizira izmenjeni kod za performance probleme — N+1 upiti, nepotrebni renderovi.',
    category: 'Kvalitet',
    whenUsed: 'Kada izmene mogu uticati na performanse (upiti, renderovanje, veliki nizovi).',
    example: 'Petlja u petlji za bazu → "N+1 upit detektovan, koristi include umesto pojedinačnih upita"',
    calledBy: 'Uslovno od strane code-reviewer-a',
  },
  {
    name: 'debugger',
    icon: '🐛',
    description: 'Sistematski debuguje runtime probleme kroz 5 faza — reproduce, isolate, identify, propose, verify.',
    category: 'Workflow',
    whenUsed: 'Kada nešto ne radi, a nije failing test. Pokreće se kroz /debug komandu.',
    example: '/debug "login ne radi" → reprodukuje → izoluje → identifikuje → predlaže fix → verifikuje',
    calledBy: 'Korisnik preko /debug',
  },
  {
    name: 'verification-orchestrator',
    icon: '🔄',
    description: 'Koordinira verifikacioni pipeline — test, analiza, popravka, regresija u petlji.',
    category: 'Verifikacija',
    whenUsed: 'Posle implementacije, da se proveri da sve radi. Max 3 iteracije.',
    example: 'Pokreni testove → 2 padaju → analiziraj → popravi → pokreni ponovo → sve zeleno',
    calledBy: '/ship komanda, korisnik',
  },
  {
    name: 'failure-analyzer',
    icon: '🔬',
    description: 'Analizira padajuće testove i traži root cause (ne simptom). Vraća plan popravke.',
    category: 'Verifikacija',
    whenUsed: 'Kada testovi padaju — drugi korak u verifikacionoj petlji.',
    example: 'Test pada: "expected 200, got 401" → analiza: "middleware proverava token koji test ne šalje"',
    calledBy: 'verification-orchestrator',
  },
  {
    name: 'bug-fixer',
    icon: '🔧',
    description: 'Primenjuje minimalne popravke koda na osnovu analize. Samo za risk:low izmene.',
    category: 'Verifikacija',
    whenUsed: 'Kada failure-analyzer identifikuje problem sa niskim rizikom popravke.',
    example: 'Fali import u test fajlu → bug-fixer doda import, ništa drugo ne dira',
    calledBy: 'verification-orchestrator',
  },
  {
    name: 'regression-tester',
    icon: '🧪',
    description: 'Poslednji korak verifikacije — pun test suite, lint, build, provera opsega izmena.',
    category: 'Verifikacija',
    whenUsed: 'Pre commit-a, da potvrdi da ništa postojeće nije pokvareno.',
    example: 'npm test + npm run lint + npm run build — sve zeleno → safe to commit',
    calledBy: 'verification-orchestrator, /ship',
  },
  {
    name: 'commit-message-formatter',
    icon: '💬',
    description: 'Formatira commit poruku prema Conventional Commits standardu.',
    category: 'Održavanje',
    whenUsed: 'Pre svakog commit-a. Osigurava dosledan format.',
    example: '"dodao login" → "feat: add user login endpoint with JWT authentication"',
    calledBy: '/ship komanda',
  },
  {
    name: 'pr-description-writer',
    icon: '📝',
    description: 'Piše opis Pull Request-a na osnovu commit-a i izmena.',
    category: 'Održavanje',
    whenUsed: 'Kada se kreira PR. Automatski generiše summary i test plan.',
    example: 'PR: ## Summary\\n- Add user auth\\n- JWT tokens\\n## Test plan\\n- Login/register tests pass',
    calledBy: '/ship komanda',
  },
  {
    name: 'docs-writer',
    icon: '📚',
    description: 'Piše ili ažurira tehničku dokumentaciju za zadati fajl/modul.',
    category: 'Održavanje',
    whenUsed: 'Kada se dodaje novi feature ili menja postojeći kod koji ima dokumentaciju.',
    example: '/docs-update backend/routes/authRoutes.js → ažurira API dokumentaciju',
    calledBy: 'Korisnik preko /docs-update',
  },
  {
    name: 'docs-reviewer',
    icon: '📑',
    description: 'Pregleda postojeću dokumentaciju i daje strukturisan feedback.',
    category: 'Održavanje',
    whenUsed: 'Posle pisanja dokumentacije ili kada korisnik traži audit.',
    example: '"Sekcija o auth-u ne pominje refresh token flow" — feedback sa predlozima',
    calledBy: 'docs-writer, korisnik',
  },
  {
    name: 'repo-explorer',
    icon: '🗺️',
    description: 'Brza navigacija kroz codebase — gde je nešto, kako je implementirano, koji pattern se koristi.',
    category: 'Workflow',
    whenUsed: 'Kada treba brzo naći fajl, razumeti strukturu, ili videti kako nešto radi. Read-only.',
    example: '"Gde je auth middleware?" → backend/middlewares/authMiddleware.js, evo šta radi...',
    calledBy: 'Bilo koji agent koji treba kontekst',
  },
];

export const AGENT_CATEGORIES = ['Workflow', 'Kvalitet', 'Verifikacija', 'Održavanje'];
