import { SkillData } from '@/components/learn/SkillCard';

export const SKILLS: SkillData[] = [
  {
    name: 'git-workflow',
    group: 'Git',
    description: 'Pravila za branching, commit, merge, konflikte i anti-paterne.',
    whenActivated: 'Pri svakoj git operaciji — commit, push, merge, branch.',
    rules: [
      'Nikad push na main direktno',
      'Feature grane iz develop',
      'Conventional Commits format',
      'Pull request sa review pre merge-a',
    ],
    example: 'git checkout -b feature/user-auth develop',
  },
  {
    name: 'commit-message-style',
    group: 'Git',
    description: 'Conventional Commits format za commit poruke.',
    whenActivated: 'Pri svakom commit-u.',
    rules: [
      'Format: tip: kratak opis na engleskom',
      'Tipovi: feat, fix, docs, refactor, test, chore',
      'Kratak opis (max 72 karaktera)',
      'Body za detalje ako je potrebno',
    ],
    example: 'feat: add user registration endpoint',
  },
  {
    name: 'error-handling-patterns',
    group: 'Pisanje koda',
    description: 'Pravila za error handling — tipovi grešaka, custom error klase, logovanje.',
    whenActivated: 'Kada se piše error handling logika ili API response.',
    rules: [
      'Centralizovani error handler (nikad response u controlleru)',
      'Standardan error response format (success, error, message)',
      'HTTP status kodovi: 400, 401, 403, 404, 500',
      'Winston za logovanje, nikad console.log u produkciji',
    ],
    example: 'throw new ValidationError("Email je obavezan")',
  },
  {
    name: 'express-mvc-patterns',
    group: 'Pisanje koda',
    description: 'MVC razdvajanje — Route → Controller → Model.',
    whenActivated: 'Pri pisanju backend koda.',
    rules: [
      'Route definiše putanje i middleware',
      'Controller sadrži logiku',
      'Model definiše strukturu podataka',
      'Nikad SQL u controlleru, nikad response u modelu',
    ],
    example: 'router.get("/users", authMiddleware, userController.getAll)',
  },
  {
    name: 'sequelize-patterns',
    group: 'Pisanje koda',
    description: 'Pravila za Sequelize modele, migracije i upite.',
    whenActivated: 'Pri radu sa bazom podataka.',
    rules: [
      'Uvek timestamps: true, paranoid: true, underscored: true',
      'Migracije za svaku promenu šeme (nikad sync)',
      'Asocijacije u models/index.js',
      'Soft delete — nikad fizičko brisanje',
    ],
    example: 'User.findAll({ where: { role: "admin" }, include: Vehicle })',
  },
  {
    name: 'api-security-patterns',
    group: 'Sigurnost',
    description: 'JWT autentifikacija, validacija inputa, CORS, rate limiting.',
    whenActivated: 'Pri radu sa autentifikacijom i API sigurnošću.',
    rules: [
      'Access token (15min) + Refresh token (7 dana)',
      'bcryptjs za hashovanje lozinki',
      'express-validator za validaciju inputa',
      'Helmet, CORS, rate-limit na svakom projektu',
    ],
    example: 'Authorization: Bearer <access_token>',
  },
  {
    name: 'dependency-management',
    group: 'Sigurnost',
    description: 'Pravila za dodavanje, ažuriranje i audit npm paketa.',
    whenActivated: 'Pre svake npm install operacije.',
    rules: [
      'Proveri da li je paket aktivan i siguran',
      'Ne instaliraj bez provere (npm audit)',
      'Frontend paketi SAMO u frontend/package.json',
      'Nikad ručno editovati package-lock.json',
    ],
    example: 'npm audit → 0 vulnerabilities',
  },
  {
    name: 'nextjs-patterns',
    group: 'Pisanje koda',
    description: 'App Router, layout, loading/error stanja i best practices.',
    whenActivated: 'Pri radu sa frontendom.',
    rules: [
      'App Router (nikad Pages Router)',
      'layout.tsx za deljeni UI',
      'loading.tsx i error.tsx za svaku rutu',
      'Server komponente po defaultu, "use client" samo kad treba',
    ],
    example: 'app/dashboard/page.tsx → /dashboard ruta',
  },
  {
    name: 'test-conventions',
    group: 'Testiranje',
    description: 'Konvencije za Jest, Supertest i React Testing Library.',
    whenActivated: 'Pri pisanju testova.',
    rules: [
      'Svaki endpoint mora imati test',
      'Test opisuje šta testira, ne kako',
      'Nikad brisati test da bi kod prošao',
      'Setup/teardown za čišćenje test baze',
    ],
    example: 'it("should return 401 when token is missing", async () => { ... })',
  },
  {
    name: 'debugging-methodology',
    group: 'Testiranje',
    description: 'Sistematska metodologija debugovanja u 5 faza.',
    whenActivated: 'Kada se traži uzrok problema.',
    rules: [
      '1. Reproduce — ponovi problem konzistentno',
      '2. Isolate — suzi opseg gde je problem',
      '3. Identify — nađi tačan uzrok',
      '4. Propose — predloži fix sa procenom rizika',
      '5. Verify — potvrdi da je fix ispravan',
    ],
    example: '/debug "login vraća 500" → 5 faza sistematskog debugovanja',
  },
  {
    name: 'tech-writing-style',
    group: 'Dokumentacija',
    description: 'Stil tehničke dokumentacije — ton, struktura, primeri.',
    whenActivated: 'Kada se piše ili pregleda dokumentacija.',
    rules: [
      'Objasni koncepte prostim jezikom',
      'Koristi analogije iz stvarnog života',
      'Svaki primer mora raditi (copy-paste)',
      'API dokumentacija: metod, URL, body, response',
    ],
    example: 'JWT je kao propusnica na koncertu — jednom se verifikuješ, posle samo pokazuješ.',
  },
  {
    name: 'docs-validator',
    group: 'Dokumentacija',
    description: 'Proverava da li su komande, putanje i linkovi u dokumentaciji tačni.',
    whenActivated: 'Pre commit-a dokumentacije.',
    rules: [
      'Sve komande moraju biti tačne i pokretljive',
      'Putanje do fajlova moraju postojati',
      'Verzije biblioteka moraju biti ažurne',
      'Linkovi ne smeju biti pokvareni',
    ],
    example: 'npm run dev → proverava da skripta postoji u package.json',
  },
  {
    name: 'changelog-updater',
    group: 'Dokumentacija',
    description: 'Prevodi commit poruke u CHANGELOG.md zapise.',
    whenActivated: 'Pre release-a ili kroz /ship komandu.',
    rules: [
      'Grupisanje po tipu: Added, Changed, Fixed',
      'Linkovi na PR/issue',
      'Datum release-a',
      'Semantic versioning (MAJOR.MINOR.PATCH)',
    ],
    example: '## [1.2.0] - 2025-06-15\\n### Added\\n- User registration endpoint',
  },
  {
    name: 'pr-description-style',
    group: 'Dokumentacija',
    description: 'Format i pravila za opis Pull Request-a.',
    whenActivated: 'Pri kreiranju PR-a.',
    rules: [
      '## Summary — šta je promenjeno',
      '## Test plan — kako testirati',
      'Linkovi na relevantan issue',
      'Screenshot za UI promene',
    ],
    example: '## Summary\\n- Add login page\\n## Test plan\\n- [ ] Login with valid credentials',
  },
  {
    name: 'css/tailwind-patterns',
    group: 'Pisanje koda',
    description: 'Tailwind konvencije — responsive, dark tema, custom klase.',
    whenActivated: 'Pri radu sa stilovima na frontendu.',
    rules: [
      'Mobile-first: bazni stilovi za mobile, sm: za tablet, lg: za desktop',
      'Nikad vanilla CSS (osim globals.css)',
      'Koristiti Tailwind klase direktno, @apply samo izuzetno',
      'Custom boje u tailwind.config.js ako treba',
    ],
    example: 'className="flex flex-col md:flex-row gap-4 p-4 md:p-6"',
  },
];

export const SKILL_GROUPS = ['Git', 'Pisanje koda', 'Sigurnost', 'Testiranje', 'Dokumentacija'];
