import { TechCardData } from '@/components/learn/TechCard';

export const TECH_STACK: TechCardData[] = [
  // Frontend
  {
    name: 'React',
    icon: '⚛️',
    category: 'Frontend',
    shortDescription: 'JavaScript biblioteka za pravljenje korisničkih interfejsa',
    analogy: 'React je kao LEGO kockice za web stranice. Svaka komponenta je jedna kockica — dugme, forma, kartica. Sklapaš ih zajedno da napraviš celu stranicu.',
    whereInCode: 'frontend/components/, frontend/app/',
    details: 'React koristi "komponente" — male, samostalne celine koje imaju svoj izgled i ponašanje. Umesto da pišeš celu stranicu u jednom fajlu, razbijash je na delove. LoginForm je jedna komponenta, Header druga, Dashboard treća.',
  },
  {
    name: 'Next.js',
    icon: '▲',
    category: 'Frontend',
    shortDescription: 'React framework sa routing-om, SSR-om i optimizacijama',
    analogy: 'Ako je React motor, Next.js je ceo automobil. Dodaje routing (stranice), server-side rendering (brže učitavanje), i gomilu optimizacija koje bi inače morao sam da praviš.',
    whereInCode: 'frontend/app/ (App Router), frontend/middleware.ts',
    details: 'Next.js koristi App Router — fajl-bazirani routing. Fajl app/login/page.tsx automatski postaje stranica /login. Podržava SSR, SSG, ISR i CSR rendering strategije.',
  },
  {
    name: 'Tailwind CSS',
    icon: '🎨',
    category: 'Frontend',
    shortDescription: 'Utility-first CSS framework za brz styling',
    analogy: 'Umesto da pišeš CSS pravila u posebnom fajlu, Tailwind ti daje gotove "mini-stilove" koje kačiš direktno na HTML elemente. `bg-blue-500` = plava pozadina, `text-lg` = veći tekst.',
    whereInCode: 'Klase na svim komponentama, frontend/tailwind.config.js',
    details: 'Tailwind eliminiše potrebu za pisanjem custom CSS-a. Sve se radi kroz utility klase: layout (flex, grid), spacing (p-4, m-2), boje (bg-gray-900), responsive (md:flex-row).',
  },
  {
    name: 'TypeScript',
    icon: '🔷',
    category: 'Frontend',
    shortDescription: 'JavaScript sa tipovima — manje grešaka, bolja auto-dopuna',
    analogy: 'TypeScript je kao spell-checker za kod. JavaScript ti dozvoljava da napišeš "2 + \'banana\'" bez upozorenja. TypeScript ti kaže "hej, sabiraš broj i tekst — da li si siguran?"',
    whereInCode: 'Svi .ts i .tsx fajlovi, tsconfig.json',
    details: 'Definiše tipove podataka: string, number, boolean, custom interfejsi. Editor ti daje auto-complete i upozorava na greške PRE nego što pokreneš kod.',
  },
  // Backend
  {
    name: 'Node.js',
    icon: '🟢',
    category: 'Backend',
    shortDescription: 'JavaScript runtime — pokreće JS izvan browsera',
    analogy: 'Browser pokreće JavaScript na tvom računaru. Node.js pokreće JavaScript na SERVERU. Isti jezik, dva različita mesta.',
    whereInCode: 'Ceo backend/ folder',
    details: 'Node.js koristi V8 engine (isti koji Chrome koristi) da pokrene JavaScript na serveru. Asinhroni, event-driven — odličan za API servere.',
  },
  {
    name: 'Express.js',
    icon: '🚂',
    category: 'Backend',
    shortDescription: 'Minimalistički web framework za Node.js',
    analogy: 'Express je kao recepcioner u hotelu. Dočekuje zahteve (HTTP request), usmerava ih na pravo mesto (route → controller), i šalje odgovor nazad.',
    whereInCode: 'backend/app.js, backend/routes/',
    details: 'Express koristi middleware pattern — svaki zahtev prolazi kroz lanac funkcija (auth, logging, validation) pre nego što stigne do kontrolera.',
  },
  {
    name: 'Sequelize',
    icon: '🗃️',
    category: 'Backend',
    shortDescription: 'ORM za komunikaciju sa bazom podataka',
    analogy: 'Umesto da pišeš SQL upite ručno ("SELECT * FROM users WHERE..."), Sequelize ti daje JavaScript metode: User.findAll(), User.create(). On prevodi tvoj JS u SQL.',
    whereInCode: 'backend/models/, backend/migrations/, backend/config/database.js',
    details: 'Sequelize definiše modele (šta sadrži tabela), asocijacije (veze između tabela), i migracije (verzionisanje šeme baze). Podržava MySQL, PostgreSQL, SQLite.',
  },
  {
    name: 'MySQL',
    icon: '🐬',
    category: 'Backend',
    shortDescription: 'Relaciona baza podataka',
    analogy: 'MySQL je kao ogromna Excel tabela, ali mnogo moćnija. Ima tabele (users, vehicles), kolone (name, email), i redove (svaki korisnik je jedan red). Plus veze između tabela.',
    whereInCode: 'backend/config/database.js, backend/migrations/',
    details: 'Relaciona baza — podaci su organizovani u tabele sa definisanom strukturom. ACID compliance znači da su podaci uvek konzistentni.',
  },
  // Alati
  {
    name: 'JWT',
    icon: '🔐',
    category: 'Alati',
    shortDescription: 'JSON Web Token — autentifikacija bez sesija',
    analogy: 'JWT je kao propusnica na koncertu. Jednom kad se verifikuješ (login), dobiješ propusnicu (token). Pokazuješ je na svakom ulazu (zahtev) bez ponovnog dokazivanja identiteta.',
    whereInCode: 'backend/utils/tokenHelper.js, backend/middlewares/authMiddleware.js',
    details: 'Access token (15 min, za API pozive) + Refresh token (7 dana, za obnavljanje access tokena). bcryptjs hashuje lozinke pre čuvanja u bazi.',
  },
  {
    name: 'Git',
    icon: '📦',
    category: 'Alati',
    shortDescription: 'Sistem za verzionisanje koda',
    analogy: 'Git je kao "Ctrl+Z" za ceo projekat, ali mnogo moćniji. Svaka promena se čuva kao "commit" (snimak), i možeš se vratiti na bilo koji prethodni snimak.',
    whereInCode: '.git/ folder, .gitignore',
    details: 'Branching (paralelni razvoj), merge (spajanje promena), pull request (code review pre spajanja). Main → develop → feature/* workflow.',
  },
  {
    name: 'Jest',
    icon: '🃏',
    category: 'Alati',
    shortDescription: 'Testing framework za JavaScript',
    analogy: 'Jest je kao kontrolor kvaliteta u fabrici. Proverava svaki deo proizvoda pre nego što izađe iz pogona. "Da li login radi?" — Jest to proverava automatski.',
    whereInCode: 'backend/tests/, frontend/__tests__/',
    details: 'Unit testovi (pojedinačne funkcije), integracioni testovi (API endpointi sa Supertest), frontend testovi (React Testing Library).',
  },
  {
    name: 'Swagger',
    icon: '📖',
    category: 'Alati',
    shortDescription: 'Automatska API dokumentacija',
    analogy: 'Swagger je kao meni u restoranu za tvoj API. Umesto da pogađaš "koji endpoint postoji i šta prima" — Swagger ti sve pokazuje i dozvoljava da probaš odmah.',
    whereInCode: 'http://localhost:5000/api-docs, swagger anotacije u routes/',
    details: 'Automatski generisana dokumentacija iz koda. Interaktivni UI — možeš slati zahteve direktno iz browsera.',
  },
];
